Update `OAuthlib` to version `3.2.0`
AnacondaRecipes/oauthlib-feedstock pull request #2
Opened 2022-02-03 15:24 UTC by varlackc

`oauthlib` version `3.2.0`
1. - [x] check the upstream
    https://github.com/oauthlib/oauthlib/tree/v3.2.0

2. - [x] check the pinnings
 
   https://github.com/oauthlib/oauthlib/blob/v3.2.0/setup.py

    the minimal version of `python` supported is `3.6`
    https://github.com/oauthlib/oauthlib/blob/v3.2.0/setup.py#L37

3. - [x] check the changelogs

https://github.com/oauthlib/oauthlib/blob/v3.2.0/CHANGELOG.rst

Most of the changes mentioned were new features added

4. - [x] additional research
    https://github.com/conda-forge/oauthlib-feedstock/issues

    There are currently no open issues mentioned in `conda-forge`

5. - [x] verify dev_url
    https://github.com/idan/oauthlib

6. - [x] verify doc_url
    https://oauthlib.readthedocs.io

7. - [x] license is spdx compliant
8. - [x] license family
9. - [x] verify the build number
     the build number is set to zero
10. - [x] verify setuptools
     `setuptools` is on the recipe
11. - [x] verify wheel
     `wheel` is on the recipe
12. - [x] pip in the test section
     `pip` is on the recipe
13. - [x] veriy the test section

Results:
- All checks have passed

Based on the research findings and the results we can conclude
that it is safe to update `oauthlib` to version `3.2.0`

2022-02-03 17:54 UTC, ScottBailey approved these changes
lgtm

2022-02-03 19:15 UTC, chenghlee approved these changes

2022-02-04 06:03 UTC, skupr-anaconda requested changes
I think it's better to remove the upper version of cryptography `<4`, because in the test environment it uses now `3.4.8` but we have the latest version **36.0.0**.
So use `cryptography >=3.0.0` and **not** `cryptography >=3.0.0,<4`

2022-02-07 16:22 UTC, skupr-anaconda approved these changes

2022-02-08 14:54 UTC, merged